CREATE DATABASE SsdShop;

USE SsdShop;

CREATE TABLE Products (
	Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	Maker VARCHAR(250) NOT NULL,
	CapacityInGb INT NOT NULL,
	FormFactor INT NOT NULL,
	ReadingSpeed INT NOT NULL,
	WritingSpeed INT NOT NULL,
	Price INT NOT NULL
);